---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Excitevent"
host: "4vx9iv55pk.execute-api.us-east-1.amazonaws.com"
basePath: "/test"
schemes:
- "https"
paths:
  /event/createEvent:
    post:
      parameters:
      - name: "Content-Type"
        in: "header"
        required: false
        type: "string"
      - name: "x-amz-meta-name"
        in: "header"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /event/findByTags:
    get:
      operationId: "findEventsByTags"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/ArrayOfEvent"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /event/myevents:
    get:
      responses:
        "200":
          description: "200 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /event/{eventId}:
    get:
      operationId: "getEventById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Event"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
        "404":
          description: "404 response"
    post:
      parameters:
      - name: "Content-Type"
        in: "header"
        required: false
        type: "string"
      - name: "eventId"
        in: "path"
        required: true
        type: "string"
      - name: "x-amz-meta-name"
        in: "header"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    delete:
      operationId: "deleteEvent"
      parameters:
      - name: "eventId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /event/{eventId}/invite:
    get:
      parameters:
      - name: "eventId"
        in: "path"
        required: true
        type: "string"
      - name: "userid"
        in: "query"
        required: true
        type: "string"
      - name: "emails"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /store/deleteorder:
    delete:
      parameters:
      - name: "userId"
        in: "query"
        required: false
        type: "string"
      - name: "eventId"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /store/hasticket:
    get:
      responses:
        "200":
          description: "200 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /store/inventory:
    get:
      operationId: "getInventory"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/MODEL5f34e5"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /store/mytickets:
    get:
      parameters:
      - name: "userId"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /store/order:
    post:
      operationId: "placeOrder"
      consumes:
      - "application/xml"
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "query"
        required: false
        type: "string"
      - name: "eventId"
        in: "query"
        required: false
        type: "string"
      - in: "body"
        name: "Order"
        required: true
        schema:
          $ref: "#/definitions/Order"
      - in: "body"
        name: "Order"
        required: true
        schema:
          $ref: "#/definitions/Order"
      - in: "body"
        name: "Order"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Order"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "405":
          description: "405 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /store/order/{orderId}:
    get:
      operationId: "getOrderById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "orderId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Order"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
        "404":
          description: "404 response"
    delete:
      operationId: "deleteOrder"
      parameters:
      - name: "orderId"
        in: "path"
        required: true
        type: "string"
      responses:
        "400":
          description: "400 response"
        "404":
          description: "404 response"
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "orderId"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /user/click:
    post:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /user/create:
    post:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /user/login:
    get:
      operationId: "loginUser"
      parameters:
      - name: "password"
        in: "query"
        required: false
        type: "string"
      - name: "username"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            X-Rate-Limit:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
            X-Expires-After:
              type: "string"
        "400":
          description: "400 response"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /user/recommend:
    get:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /user/{uni}:
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "uni"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
    x-amazon-apigateway-any-method:
      parameters:
      - name: "uni"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      eventId:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  Event:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      date:
        type: "string"
        format: "date"
      time:
        type: "string"
        format: "time"
      location:
        type: "string"
      description:
        type: "string"
      peers:
        type: "array"
        items:
          $ref: "#/definitions/Event"
      category:
        $ref: "#/definitions/Category"
      photoUrls:
        type: "array"
        items:
          type: "string"
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "event status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
  MODEL5f34e5:
    type: "object"
    additionalProperties:
      type: "integer"
      format: "int32"
  ArrayOfEvent:
    type: "array"
    items:
      $ref: "#/definitions/Event"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
